name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Cordova SMS plugin
      run: |
        npm install cordova-sms-plugin
        mkdir -p plugins
        git clone https://github.com/cordova-sms/cordova-sms-plugin.git plugins/cordova-sms-plugin

    - name: Build web assets
      run: npm run build

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli

    - name: Add Android platform
      run: npx cap add android

    - name: Update Android platform
      run: npx cap sync android
    
    - name: Copy data files to Android assets
      run: |
        mkdir -p android/app/src/main/assets/public/data
        cp -r data/* android/app/src/main/assets/public/data/ || echo "No data files to copy"

    - name: Build Debug APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk